cloudflare_tunnel_token: ENC[AES256_GCM,data:MhbPbpIrcDBzPnS37dR/S4sf5UT2Hn2gWp2rg7xBKtoJ5Mj6e9XiIm4E6qhVH3w2iNPcmKbc1ym1IQeDvKnHajdAUxtY+gtwP4yy2ila7i0eY9OexwMYYdmTVjZzgBdIT/P5l/Ao7gRldXeq6wIh4Qpx9fMCP+CYwEhnYMe2vELJGoQwce1TH1QNgq3pg94vTio0JYzMAnzRZ+bdnqMIVCETneOSDwoXFCOBqTgTaxbUpRsw,iv:h9QzeExlWVk6fLpwOUCXTiKzcIddRahN/c6Fjd/Co5U=,tag:ZzGV5PtYHAikM0j/j2X76g==,type:str]
cloudflare_dns_api_token: ENC[AES256_GCM,data:YUp3C/yikWzUZ+e20QDFDChmEgNIEoVjjylxWGx87S6pIl6cxnZHycn9BjHVPHqp5OmeHE8=,iv:XHDVjfOHAEKB3iBHfeDw0bwnFv9lu/53CnzpA1Y8F/8=,tag:zFHDAbigidrjlHAyKkdp6w==,type:str]
sops:
    age:
        - recipient: age1s0gmt47hc9fktm9juqafyp5s0ptnsc933cg0wwq3x5e83ehk0pzq06u9qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YnNSRG9va0pRLzJQalkz
            U2x1N2NQSU9PQUlDOWxhK2duVXZHemplekRBCitWSko0S0hxc2c3dElrdFpSMzFB
            YlVSMThtWVBWSHYxZW40K0g3akdFSlUKLS0tIGNFNmtYcEt3d3NzTlB4WnByd1pK
            dHNQd1QraHNmY1c4c2E2ZFdYa2hRblEKgX4UMkYTLKznrzZ73QJVBn78R397mhu1
            NME2G8E89ufYR8kVX6YI2vwwj/O7adZiVT0a7TbF0NnCp2TSIqKpzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T11:05:18Z"
    mac: ENC[AES256_GCM,data:H+nWcF+acDSx69a9OAeSyjOYAT/Id80tQKSKp4yqrR0QnDH1J8R5LxFyfCTjAT4el1NSJ0HuOqv8vSDjJbZNTaw7Tnhfkyv2TA9xkHUtobmPpwV3kZUGpAK0gdCps4DeTT2K4umyk6nVb02QaFVqo1L5So7cya4iJFVbb1fQ7yM=,iv:hpS9GQcGCGq0NiSmmO49PwGoyuvCDGWaGCFumeLOJ8k=,tag:k8fXLHJNGo0iPYELdeQJ9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
