- name: Install workstation_packages
  ansible.builtin.package:
    name: "{{ workstation_packages }}"
    state: present 

- name: Install workstation_aur_packages
  ansible.builtin.command:
    cmd: yay -S --noconfirm --needed {{ item }}
  changed_when: false
  become: false 
  loop: "{{ workstation_aur_packages }}"

- name: Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create node-exporter directory
  ansible.builtin.file:
    path: /opt/homelab/node-exporter
    state: directory
    mode: '0755'

- name: Deploy node-exporter Compose
  ansible.builtin.template:
    src: node-exporter/docker-compose.yml.j2
    dest: /opt/homelab/node-exporter/docker-compose.yml

- name: Enable and start SDDM                                                                                                                                     
  ansible.builtin.service:                                
    name: sddm 
    state: started
    enabled: true

- name: Enable and start Bluetooth                                                                                                                                     
  ansible.builtin.service:                                
    name: bluetooth 
    state: started
    enabled: true

- name: Enable and start auto-cpufreq                                                                                                                          
  ansible.builtin.service:                                
    name: auto-cpufreq 
    state: started
    enabled: true

- name: Deploy SDDM config 
  ansible.builtin.template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
  notify: Restart SDDM 
