ssh_service: sshd

workstation_packages:
  - hyprland
  - hypridle
  - hyprlock
  - hyprpaper
  - hyprpolkitagent
  - hyprshade
  - hyprlauncher
  - kitty
  - neovim
  - zsh
  - zsh-autosuggestions
  - starship
  - rofi
  - dunst
  - firefox
  - blueman
  - bluez
  - bluez-utils
  - brightnessctl
  - btop
  - dolphin
  - grim
  - slurp
  - swappy
  - swaybg
  - pamixer
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - wireplumber
  - gst-plugin-pipewire
  - libpulse
  - libnotify
  - libva-nvidia-driver
  - nvidia-open-dkms
  - nvidia-settings
  - dkms
  - polkit-gnome
  - polkit-kde-agent
  - power-profiles-daemon
  - qt5-wayland
  - qt6-wayland
  - qt6ct
  - qqc2-desktop-style
  - kvantum
  - sddm
  - uwsm
  - wl-clipboard
  - wofi
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-kde
  - xorg-server
  - xorg-xinit
  - inter-font
  - ttf-cascadia-code
  - ttf-manrope
  - papirus-icon-theme
  - woff2-font-awesome
  - network-manager-applet
  - networkmanager
  - wpa_supplicant
  - khal
  - vdirsyncer
  - snapper
  - btrfs-progs
  - smartmontools
  - auto-cpufreq
  - yazi
  - ffmpegthumbnailer
  - poppler
  - stow
  - nodejs
  - npm
  - nmap
  - webkit2gtk-4.1
  - volantes-cursors-git

workstation_aur_packages:
  - yay
  - waybar-git
  - grimblast-git
  - hyprpicker-git
  - quickshell-git
  - waypaper-git
  - howdy-git
